// Types that mirror a Rust struct are generated by tauri-specta into
// `$lib/bindings.ts` (run `deno task typegen`) and re-exported here so callers
// keep importing from `$lib/types`. Hand-written types below either narrow a
// generated one (literal unions the Rust side stores as plain strings) or
// describe Codex app-server JSON that has no Rust struct.
import type {
  AgentRunRow,
  AgentSettingsPayload,
  BranchRef,
  CodexNotification,
  CommitInfo,
  Connection,
  FileMatch,
  SubagentDetail as GenSubagentDetail,
  HandoffPreflight,
  Project,
  RecentHomeInfo,
  SearchFilter,
  SearchGroup,
  ServerRequest,
  SiblingRef,
  StoredPlacement,
  StoredProjectSource,
  StoredSidebarFolder,
  StoredThreadSection,
  ThreadMatch,
  ThreadSummary,
  WorkspaceResults,
  WorktreeBranch,
} from "$lib/bindings";

export type {
  Account,
  Attachment,
  BinaryStatus,
  BootstrapData,
  ChangedFile,
  ChangesSummary,
  ChecksSummary,
  ConfigSetting,
  CreateWorkspaceInput,
  DiffHunk,
  DiffLine,
  FileDiff,
  FileHit,
  GitRepoInfo,
  GitStatus,
  HomeOverview,
  IntegrationsList,
  LaunchState,
  McpServerInfo,
  McpServerSummary,
  PendingComment,
  PluginSummary,
  PrComment,
  PrCommit,
  PrDetail,
  PrFile,
  PrFreshness,
  Project,
  ProviderStatus,
  PrSummary,
  ReviewDraft,
  RuntimeSettings,
  SettingKind,
  SettingSource,
  SidebarLayout,
  SideQuestion,
  SkillInfo,
  SkillSummary,
  StatusCounts,
  StatusFile,
  ThreadSearchItem,
  ThreadSearchPage,
  ThreadSummary,
  ThreadsPage,
  WireMessage,
  WorkspaceMember,
  WorkspaceMemberInput,
  WorktreeEntry,
} from "$lib/bindings";

export type ThreadSection = StoredThreadSection;

export type ProjectSource = StoredProjectSource;

export type WorkspaceFileMatch = FileMatch;

export type WorkspaceThreadMatch = ThreadMatch;

export type WorkspaceSearchGroup<T> = SearchGroup<T>;

export type WorkspaceSearchResults = WorkspaceResults;

export type SidebarFolder = StoredSidebarFolder;

export type SidebarPlacement = StoredPlacement;

export type SidebarItemRef = SiblingRef;

export type MenuTarget =
  | { kind: "project"; project: Project }
  | { kind: "thread"; project: Project; thread: ThreadSummary }
  | { kind: "section"; section: ThreadSection }
  | { kind: "folder"; folder: SidebarFolder; project: Project | null };

export type MenuAction =
  | "reveal"
  | "rename"
  | "togglePin"
  | "toggleArchive"
  | "archive"
  | "delete"
  | "remove"
  | "moveUp"
  | "moveDown"
  | "moveToWorkspace"
  | "moveToSection"
  | "deleteSection"
  | "newFolder"
  | "deleteFolder"
  | "fork"
  | "createWorktree"
  | "openDetails";

/**
 * One item of a `turn/start` input as the app-server defines it
 * (`app-server-protocol` v2 `UserInput`, `text_elements` defaulted server-side).
 * Deliberately strict: a `skill` without a `path` once shipped and was only
 * rejected at runtime, so outbound builders type against this union rather
 * than the loose `UserInputPart` used for reading messages back.
 */
export type TurnInputItem =
  | { type: "text"; text: string }
  | { type: "image"; url: string; detail?: "low" | "high" | "original" | "auto" }
  | { type: "localImage"; path: string; detail?: "low" | "high" | "original" | "auto" }
  | { type: "audio"; url: string }
  | { type: "localAudio"; path: string }
  | { type: "skill"; name: string; path: string }
  | { type: "mention"; name: string; path: string };

/** A user message part as read back from Codex; loose because it may carry
 * types and fields the app does not model. Send with `TurnInputItem`. */
export interface UserInputPart {
  type: string;
  text?: string;
  url?: string;
  path?: string;
  name?: string;
}

/** The goal a long-running thread is working towards (`/goal`). */
export interface ThreadGoal {
  threadId: string;
  objective: string;
  status: "active" | "paused" | "blocked" | "usageLimited" | "budgetLimited" | "complete" | (string & {});
  tokenBudget: number | null;
  tokensUsed: number;
  timeUsedSeconds: number;
}

export interface FileUpdateChange {
  path: string;
  kind: { type: string; movePath?: string | null };
  diff: string;
}

/** One step of the todo list Codex maintains for the turn it is working on. */
export interface TurnPlanStep {
  step: string;
  status: "pending" | "inProgress" | "completed";
}

export interface TurnPlan {
  turnId: string;
  explanation: string | null;
  steps: TurnPlanStep[];
}

/**
 * The extra access Codex is asking for on an `item/permissions/requestApproval`.
 * Granting means echoing the same profile back; declining means sending an
 * empty one.
 */
export interface RequestPermissionProfile {
  network?: { enabled?: boolean } | null;
  fileSystem?: {
    read?: string[] | null;
    write?: string[] | null;
    entries?: { path: FileSystemPath; access: string }[] | null;
  } | null;
}

export type FileSystemPath = { path?: string; pattern?: string; value?: string };

/** The `form`-mode schema an MCP elicitation asks the app to draw fields for. */
export interface McpElicitationSchema {
  type: "object";
  properties: Record<string, McpElicitationField>;
  required?: string[];
}

/**
 * One field of an elicitation form. Upstream models these as untagged unions,
 * so a field is identified by `type` plus which of the choice shapes it
 * carries: `enum` (+ optional `enumNames`) or `oneOf` for a single select,
 * `type: "array"` with `items` for a multi select.
 */
export interface McpElicitationField {
  type: "string" | "number" | "integer" | "boolean" | "array";
  title?: string;
  description?: string;
  enum?: string[];
  enumNames?: string[];
  oneOf?: McpElicitationOption[];
  items?: { type?: string; enum?: string[]; anyOf?: McpElicitationOption[]; oneOf?: McpElicitationOption[] };
  default?: string | number | boolean | string[];
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
  format?: string;
}

export interface McpElicitationOption {
  const: string;
  title: string;
}

/**
 * Every item type this app knows about: the `ThreadItem` variants the
 * app-server v2 protocol defines, plus `userInputAnswered`, which the app
 * builds itself because Codex's thread projection has no item for an answered
 * question.
 *
 * Codex adds item types faster than this app adopts them, so an item's `type`
 * is still any string — see `ThreadItem.type`. What this list buys is the
 * exhaustiveness check in `turnSegments.ts`: adding a member here without
 * saying how it should be drawn fails the build.
 */
export const THREAD_ITEM_TYPES = [
  "userMessage",
  "hookPrompt",
  "agentMessage",
  "plan",
  "reasoning",
  "commandExecution",
  "fileChange",
  "mcpToolCall",
  "dynamicToolCall",
  "collabAgentToolCall",
  "subAgentActivity",
  "webSearch",
  "imageView",
  "imageGeneration",
  "sleep",
  "enteredReviewMode",
  "exitedReviewMode",
  "contextCompaction",
  "userInputAnswered",
] as const;

export type KnownThreadItemType = (typeof THREAD_ITEM_TYPES)[number];

export interface ThreadItem {
  /**
   * Deliberately open: a type Codex added after this app last caught up still
   * has to round-trip through the store and the journal. `KnownThreadItemType`
   * narrows the ones the app actually handles.
   */
  type: KnownThreadItemType | (string & {});
  id: string;
  /**
   * `userMessage` carries its parts here; `reasoning` carries the model's
   * unabridged reasoning here, as plain strings. Codex reuses the field name
   * across both item types, so the type has to cover both — read the reasoning
   * side through `reasoningContent`.
   */
  content?: UserInputPart[] | string[];
  // agentMessage / plan
  text?: string;
  // set while agentMessage deltas are still arriving; cleared when the item
  // completes, so the transcript knows when Codex went quiet to do tool work
  streaming?: boolean;
  // hookPrompt
  fragments?: { text: string; hookRunId?: string }[];
  // reasoning: the version shown by default; the unabridged one lives in
  // `content` above, behind an expander
  summary?: string[];
  /**
   * Codex's own risk assessment of this action, from
   * `item/autoApprovalReview/completed`. Explains a command that was blocked
   * without the user ever being asked.
   */
  guardianReview?: {
    status: string;
    riskLevel?: string | null;
    userAuthorization?: string | null;
    rationale?: string | null;
  };
  // commandExecution
  command?: string;
  cwd?: string;
  status?: string;
  aggregatedOutput?: string | null;
  exitCode?: number | null;
  durationMs?: number | null;
  // fileChange
  changes?: FileUpdateChange[];
  // mcpToolCall / dynamicToolCall
  server?: string;
  tool?: string;
  /** Latest progress line from a long-running MCP tool; gone once it finishes. */
  progress?: string;
  /** What the model passed the tool. Present on `dynamicToolCall`. */
  arguments?: Record<string, unknown>;
  // webSearch
  query?: string;
  // userInputAnswered
  questions?: {
    id: string;
    header?: string;
    question: string;
    isSecret?: boolean;
    options?: { label: string; description?: string }[] | null;
  }[];
  answers?: Record<string, { answers: string[] }>;
  // set when the user skipped the questions and steered Codex in their own words
  steer?: string;
  // set when the session ended before the question was answered; the original
  // request is gone, so it can only be answered as a new turn
  unanswered?: boolean;
  // set when the user gave up on a question stranded that way
  dismissed?: boolean;
  // subAgentActivity: "started" | "interacted" | "interrupted"
  kind?: string;
  agentThreadId?: string;
  agentPath?: string;
  // imageView (sleep reuses durationMs above)
  path?: string;
  // imageGeneration
  revisedPrompt?: string | null;
  savedPath?: string;
  // enteredReviewMode / exitedReviewMode
  review?: string;
  // collabAgentToolCall
  senderThreadId?: string;
  receiverThreadIds?: string[];
  prompt?: string | null;
  model?: string | null;
  reasoningEffort?: string | null;
  agentsStates?: Record<string, { status: string; message?: string | null }>;
}

export interface Turn {
  id: string;
  items: ThreadItem[];
  status: string;
  error?: { message: string } | null;
  startedAt?: number | null;
  completedAt?: number | null;
  durationMs?: number | null;
  /** What the turn ran on, as the composer resolved it; absent on older turns. */
  model?: string | null;
  reasoningEffort?: string | null;
}

/** One side of `thread/tokenUsage/updated` — either the session total or the last request. */
export interface TokenUsageBreakdown {
  totalTokens: number;
  inputTokens: number;
  cachedInputTokens: number;
  cacheWriteInputTokens?: number;
  outputTokens: number;
  reasoningOutputTokens: number;
}

export interface ThreadTokenUsage {
  total: TokenUsageBreakdown;
  last: TokenUsageBreakdown;
  modelContextWindow?: number | null;
}

/** One row of the per-model usage breakdown in `ThreadUsage`. */
export interface ThreadUsageBreakdownGroup {
  model?: string | null;
  reasoningEffort?: string | null;
  speed?: string | null;
  estimatedUsageCreditsMicros: number;
  netNewInputTokens?: number | null;
  cachedInputTokens?: number | null;
  inputTokens?: number | null;
  outputTokens?: number | null;
  totalTokens?: number | null;
}

/** `threadUsage` from `account/usage/read` when called with a `threadId`. */
export interface ThreadUsage {
  threadId: string;
  estimatedUsageCreditsMicros: number;
  estimatedUsageUsdMicros?: number | null;
  groups: ThreadUsageBreakdownGroup[];
}

/** A message waiting in the server-side thread queue (`thread/queue/*`). */
export interface QueuedSubmission {
  id: string;
  input: UserInputPart[];
  clientUserMessageId: string;
}

/** One rolling rate-limit window from `account/rateLimits/read`. */
export interface RateLimitWindow {
  usedPercent: number;
  /** Window length in minutes — 300 for the 5h limit, 10080 for the weekly one. */
  windowDurationMins?: number | null;
  /** Unix seconds at which the window resets. */
  resetsAt?: number | null;
}

export interface RateLimitSnapshot {
  limitId?: string | null;
  limitName?: string | null;
  primary?: RateLimitWindow | null;
  secondary?: RateLimitWindow | null;
  planType?: string | null;
}

/** Response of `account/rateLimits/read`. */
export interface AccountRateLimits {
  rateLimits: RateLimitSnapshot;
  rateLimitsByLimitId?: Record<string, RateLimitSnapshot> | null;
}

export interface ThreadDetail {
  id: string;
  preview: string;
  name?: string | null;
  cwd: string;
  turns: Turn[];
  subagentModelPolicy?: SubagentPolicy | null;
  subagentReasoningEffortPolicy?: SubagentPolicy | null;
}

export interface ReasoningEffortOption {
  reasoningEffort: string;
  description: string;
}

export interface Model {
  id: string;
  model: string;
  displayName: string;
  description: string;
  hidden: boolean;
  supportedReasoningEfforts: ReasoningEffortOption[];
  defaultReasoningEffort: string;
  isDefault: boolean;
  /** Id of the suggested replacement model, when this one is being upgraded away. */
  upgrade?: string | null;
  upgradeInfo?: ModelUpgradeInfo | null;
}

export interface ModelUpgradeInfo {
  model: string;
  upgradeCopy?: string | null;
  modelLink?: string | null;
  migrationMarkdown?: string | null;
  /** Unix seconds at which this model is scheduled to retire. */
  retirementAt?: number | null;
}

/** Per-turn overrides picked in the composer popovers. */
export interface TurnOptions {
  model?: string;
  effort?: string;
  approvalPolicy?: string;
  sandboxMode?: string;
  collaborationMode?: { mode: string; settings?: unknown };
  subagentModelPolicy?: SubagentPolicy | null;
  subagentReasoningEffortPolicy?: SubagentPolicy | null;
  /** What the turn will actually run on, including defaults the composer did
   *  not have to override. Recorded locally so the transcript can label each
   *  reply; not forwarded to Codex. */
  resolvedModel?: string | null;
  resolvedEffort?: string | null;
}

export type SubagentPolicy = { allowed: string[] } | { excluded: string[] };

export type SubagentDetail = GenSubagentDetail & {
  source?: "codex" | "app";
  runId?: string;
};

export type AgentRun = AgentRunRow;

/** How app-owned subagents are configured globally. */
export type AgentSettings = AgentSettingsPayload & {
  sandboxOptions: string[];
};

export interface ArchivedThread {
  id: string;
  title: string;
  cwd: string;
  updatedAt: number;
}

export interface Mention {
  name: string;
  path: string;
}

/** What the app-server reported at `initialize`. Diagnostics only. */
export interface CodexServerInfo {
  /** `<clientInfo.name>/<cli version> (<os>; <arch>) …`, e.g.
   *  `pingex/0.149.1 (Mac OS 26.6.0; arm64) (pingex; 0.1.0)`. */
  userAgent?: string | null;
  platformOs?: string | null;
  platformFamily?: string | null;
  codexHome?: string | null;
}

/** The CLI version embedded in a `userAgent`, or null when it cannot be read. */
export function codexVersionFromUserAgent(userAgent: string | null | undefined): string | null {
  const match = userAgent?.match(/^[\w.-]+\/(\d+\.\d+\.\d+(?:-[\w.]+)?)/);
  return match?.[1] ?? null;
}

export type RecentHome = RecentHomeInfo;

export type WorktreeHandoffPreflight = HandoffPreflight;

export type GitCommit = CommitInfo;

export type GitBranch = BranchRef;

/**
 * What a `/review` turn should look at. Mirrors the app-server's `ReviewTarget`
 * and is forwarded to `review/start` untouched, so the member names have to
 * stay as they are.
 */
export type ReviewTarget =
  | { type: "uncommittedChanges" }
  | { type: "baseBranch"; branch: string }
  | { type: "commit"; sha: string; title?: string | null }
  | { type: "custom"; instructions: string };

export type WorktreeBranchRequest = WorktreeBranch;

/** Payload of the `handoff://open` event when a `codex://` link is received. */
export interface HandoffOpen {
  /** "thread" | "new". */
  kind: string;
  threadId: string | null;
  path: string | null;
  /** Resolved (tilde-expanded) requested home, if the link carried one. */
  requestedHome: string | null;
  label: string | null;
  /** The requested home equals the running home (or none was supplied). */
  homeMatches: boolean;
  /** The requested home exists on disk (true when none was supplied). */
  homeExists: boolean;
}

// --- Pull-request review (provider-neutral; GitHub adapter first) ---

export interface PairingInfo {
  qrSvg: string;
  pairingCode: string;
  manualPairingCode: string | null;
  expiresAt: number | null;
}

// --- Remote connections management ---

export type RemoteConnection = Connection;

// --- Integrations (MCP servers, skills, plugins) ---

/**
 * Whether a server needs — and has — credentials.
 *
 * - `unsupported` — the server does not do auth (every stdio server).
 * - `notLoggedIn` — an OAuth server we have no token for. This is the only
 *   state where "Sign in" applies.
 * - `oAuth` — signed in via OAuth.
 * - `bearerToken` — authenticated from a `bearer_token_env_var`, so there is
 *   nothing to sign into; the credential comes from the environment.
 */
export type McpAuthStatus = "unknown" | "unsupported" | "notLoggedIn" | "bearerToken" | "oAuth" | (string & {});

/**
 * Where a server is in its lifecycle, reported by Codex builds newer than
 * 0.149.1 as `runtimeStatus`. Older builds omit it. Kept open-ended: the
 * upstream enum grows between releases and an unknown value must not break
 * the integrations list.
 */
export type McpServerRuntimeStatus =
  | "notStarted"
  | "starting"
  | "connected"
  | "authenticationRequired"
  | "failed"
  | "cancelled"
  | "disabled"
  | (string & {});

/** One tool a server exposes, as reported by `mcpServerStatus/list`. */
export interface McpTool {
  name: string;
  title?: string | null;
  description?: string | null;
  /** JSON Schema for the tool's arguments. */
  inputSchema?: McpJsonSchema | null;
  outputSchema?: McpJsonSchema | null;
}

/** The slice of JSON Schema the tool detail view reads. */
export interface McpJsonSchema {
  type?: string;
  title?: string;
  description?: string;
  properties?: Record<string, McpJsonSchema>;
  required?: string[];
  items?: McpJsonSchema;
  enum?: unknown[];
}

/**
 * Live state for one MCP server, straight from Codex. Complements
 * `McpServerSummary`, which reports what `config.toml` *declares*; this reports
 * what actually started. Joined on `name`.
 */
export interface McpServerStatus {
  name: string;
  serverInfo: {
    name: string;
    title?: string | null;
    version?: string | null;
    description?: string | null;
    websiteUrl?: string | null;
  } | null;
  /** Keyed by tool name. Empty when the server failed to start. */
  tools: Record<string, McpTool>;
  resources?: McpResource[];
  resourceTemplates?: McpResourceTemplate[];
  authStatus: McpAuthStatus;
  /** Present when the server failed to start. */
  error?: string | null;
  /** Absent on Codex ≤0.149.1. */
  runtimeStatus?: McpServerRuntimeStatus | null;
  /** Set when the server was installed by a plugin (newer Codex only). */
  pluginId?: string | null;
}

/** A concrete resource an MCP server exposes (`resources/list`). */
export interface McpResource {
  uri: string;
  name?: string | null;
  title?: string | null;
  description?: string | null;
  mimeType?: string | null;
}

/** A parameterised resource (`resources/templates/list`). */
export interface McpResourceTemplate {
  uriTemplate: string;
  name?: string | null;
  title?: string | null;
  description?: string | null;
  mimeType?: string | null;
}

// --- History search and pagination (feature 11) ---

export type ThreadSearchFilter = SearchFilter;

// --- Codex events (typed once in `src-tauri/src/codex/events.rs`) ---

/**
 * A hook run as `hook/completed` reports it. Only the fields the transcript
 * notice reads; hooks are user code and the rest is free-form.
 */
export interface HookRunSummary {
  status?: string | null;
  statusMessage?: string | null;
  eventName?: string | null;
  entries?: { kind?: string; text?: string }[] | null;
}

export interface UserInputQuestion {
  id: string;
  header: string;
  question: string;
  isOther?: boolean;
  isSecret?: boolean;
  options?: { label: string; description?: string }[] | null;
}

type ItemEventParams = { threadId: string; turnId: string; item: ThreadItem };
type DeltaEventParams = { threadId: string; turnId: string; itemId: string; delta: string };
type ReasoningEventParams = { threadId: string; turnId: string; itemId: string };

/**
 * Per-method narrowing of the generated union. The Rust decoder leaves every
 * structured payload as `unknown` and every scalar nullable; this swaps in the
 * hand-written shapes and marks required what Codex's own schema declares
 * non-optional, so reducers read `params.turn.id` without a guard.
 */
interface CodexEventOverrides {
  "thread/started": { thread: { id?: string; parentThreadId?: string | null } | null };
  "thread/status/changed": { threadId: string };
  "thread/goal/updated": { threadId: string; goal: ThreadGoal | null };
  "thread/tokenUsage/updated": { threadId: string; tokenUsage: ThreadTokenUsage | null };
  "thread/settings/updated": {
    threadId: string;
    threadSettings: {
      subagentModelPolicy?: SubagentPolicy | null;
      subagentReasoningEffortPolicy?: SubagentPolicy | null;
    } | null;
  };
  "turn/started": { threadId: string; turn: Turn };
  "turn/completed": { threadId: string; turn: Turn };
  "turn/plan/updated": { threadId: string; turnId: string; plan: TurnPlanStep[] | null };
  "item/started": ItemEventParams;
  "item/updated": ItemEventParams;
  "item/completed": ItemEventParams;
  "item/agentMessage/delta": DeltaEventParams;
  "item/plan/delta": DeltaEventParams;
  "item/commandExecution/outputDelta": DeltaEventParams;
  "item/reasoning/summaryPartAdded": ReasoningEventParams & { summaryIndex: number };
  "item/reasoning/summaryTextDelta": ReasoningEventParams & { summaryIndex: number; delta: string };
  "item/reasoning/textDelta": ReasoningEventParams & { contentIndex: number; delta: string };
  "item/commandExecution/terminalInteraction": ReasoningEventParams & { stdin: string };
  "item/mcpToolCall/progress": ReasoningEventParams & { message: string };
  "item/fileChange/patchUpdated": ReasoningEventParams & { changes: FileUpdateChange[] };
  "item/autoApprovalReview/completed": {
    threadId: string;
    turnId: string;
    review: NonNullable<ThreadItem["guardianReview"]> | null;
  };
  "hook/completed": { threadId: string; run: HookRunSummary | null };
  error: { threadId: string; error: { message?: string | null } | null };
  "account/rateLimits/updated": { rateLimits: RateLimitSnapshot | null };
}

interface ServerRequestOverrides {
  "item/fileChange/requestApproval": { changes: FileUpdateChange[] | null };
  "item/permissions/requestApproval": { permissions: RequestPermissionProfile | null };
  "item/tool/requestUserInput": { questions: UserInputQuestion[] | null };
  "mcpServer/elicitation/request": { requestedSchema: McpElicitationSchema | null };
}

type Override<E, O> = E extends { method: infer M; params: infer P }
  ? M extends keyof O
    ? { method: M; params: Omit<P, keyof O[M]> & O[M] }
    : E
  : never;

/**
 * One notification from Codex, discriminated on `method`. `disconnected` is
 * synthesised by the client when the app-server goes away.
 */
export type CodexEvent = Override<CodexNotification, CodexEventOverrides> | { method: "disconnected"; params: null };

export type CodexEventOf<M extends CodexEvent["method"]> = Extract<CodexEvent, { method: M }>;

/** A server request awaiting the user's answer, with the id to answer it under. */
export type CodexServerRequestEvent = { requestId: number } & Override<ServerRequest, ServerRequestOverrides>;
