//! The composer's golden `turn/start` inputs, generated by
//! `src/lib/composer/turnInputFixtures.test.ts` from `buildTurnInput` itself.

use serde::Deserialize;
use serde_json::Value;
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Fixture {
    pub name: String,
    pub via: String,
    pub input: Vec<Value>,
    pub expect_reply: Option<String>,
}

pub fn path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("tests")
        .join("fixtures")
        .join("protocol")
        .join("turn-inputs.json")
}

pub fn load() -> Vec<Fixture> {
    let path = path();
    let text = std::fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "{} unreadable ({error}); run `deno task test src/lib/composer/turnInputFixtures.test.ts` to generate it",
            path.display()
        )
    });
    serde_json::from_str(&text).expect("turn-inputs.json parses")
}

/// Replace `${NAME}` placeholders in every string of `value`.
pub fn substitute(value: &Value, vars: &[(&str, &str)]) -> Value {
    match value {
        Value::String(text) => {
            let mut out = text.clone();
            for (name, replacement) in vars {
                out = out.replace(&format!("${{{name}}}"), replacement);
            }
            Value::String(out)
        }
        Value::Array(items) => Value::Array(items.iter().map(|v| substitute(v, vars)).collect()),
        Value::Object(map) => Value::Object(
            map.iter()
                .map(|(k, v)| (k.clone(), substitute(v, vars)))
                .collect(),
        ),
        other => other.clone(),
    }
}
